apiVersion: v1
kind: ConfigMap
metadata:
  name: babymilk-config
  namespace: babymilk
data:
  PRODUCT_SERVICE_URL: "http://product-service:4001"
  USER_SERVICE_URL: "http://user-service:4002"
  ORDER_SERVICE_URL: "http://order-service:4003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:4004"
  UPSTREAM_TIMEOUT_MS: "10000"
  PRODUCT_SERVICE_TIMEOUT_MS: "5000"
  SEED_ON_START: "true"
  JWT_EXPIRES_IN: "24h"
  ADMIN_EMAIL: "admin@babymilk.local"
  PGHOST: "postgres"
  PGPORT: "5432"
  PGUSER: "babymilk"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CHANNEL: "order.completed"
